//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.7.3081.0.
// 

namespace Com.Unisys.CdR.Certi.Objects
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute("rispostaSir", Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class rispostaSirType
    {

        private long lottoField;

        private bool lottoFieldSpecified;

        private System.DateTime dataElaborazioneField;

        private bool dataElaborazioneFieldSpecified;

        private rispostaCreditiType rispostaCreditiField;

        private object rispostaPosteField;

        private rispostaSisalType rispostaSisalField;

        private rispostaPosteFtpType rispostaPosteFtpField;

        /// <remarks/>
        public long lotto
        {
            get
            {
                return this.lottoField;
            }
            set
            {
                this.lottoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lottoSpecified
        {
            get
            {
                return this.lottoFieldSpecified;
            }
            set
            {
                this.lottoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime dataElaborazione
        {
            get
            {
                return this.dataElaborazioneField;
            }
            set
            {
                this.dataElaborazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataElaborazioneSpecified
        {
            get
            {
                return this.dataElaborazioneFieldSpecified;
            }
            set
            {
                this.dataElaborazioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        public rispostaCreditiType rispostaCrediti
        {
            get
            {
                return this.rispostaCreditiField;
            }
            set
            {
                this.rispostaCreditiField = value;
            }
        }

        /// <remarks/>
        public object rispostaPoste
        {
            get
            {
                return this.rispostaPosteField;
            }
            set
            {
                this.rispostaPosteField = value;
            }
        }

        /// <remarks/>
        public rispostaSisalType rispostaSisal
        {
            get
            {
                return this.rispostaSisalField;
            }
            set
            {
                this.rispostaSisalField = value;
            }
        }

        /// <remarks/>
        public rispostaPosteFtpType rispostaPosteFtp
        {
            get
            {
                return this.rispostaPosteFtpField;
            }
            set
            {
                this.rispostaPosteFtpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class rispostaCreditiType
    {

        private rispostaCreditoType[] inseritiField;

        private scartoType[] scartatiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("credito", IsNullable = false)]
        public rispostaCreditoType[] inseriti
        {
            get
            {
                return this.inseritiField;
            }
            set
            {
                this.inseritiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("scarto", IsNullable = false)]
        public scartoType[] scartati
        {
            get
            {
                return this.scartatiField;
            }
            set
            {
                this.scartatiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class rispostaCreditoType
    {

        private string progPosizioneField;

        private long idPosizioneField;

        private bool idPosizioneFieldSpecified;

        private string idEventoField;

        private rataSirType[] rateField;

        private protocolloSirType[] protocolliField;

        /// <remarks/>
        public string ProgPosizione
        {
            get
            {
                return this.progPosizioneField;
            }
            set
            {
                this.progPosizioneField = value;
            }
        }

        /// <remarks/>
        public long IdPosizione
        {
            get
            {
                return this.idPosizioneField;
            }
            set
            {
                this.idPosizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPosizioneSpecified
        {
            get
            {
                return this.idPosizioneFieldSpecified;
            }
            set
            {
                this.idPosizioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string IdEvento
        {
            get
            {
                return this.idEventoField;
            }
            set
            {
                this.idEventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("rataSir", IsNullable = false)]
        public rataSirType[] rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("protocolloSir", IsNullable = false)]
        public protocolloSirType[] protocolli
        {
            get
            {
                return this.protocolliField;
            }
            set
            {
                this.protocolliField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class rataSirType
    {

        private string numeroRataField;

        private string codicePostelField;

        private string codiceSisalField;

        private string progRataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string numeroRata
        {
            get
            {
                return this.numeroRataField;
            }
            set
            {
                this.numeroRataField = value;
            }
        }

        /// <remarks/>
        public string codicePostel
        {
            get
            {
                return this.codicePostelField;
            }
            set
            {
                this.codicePostelField = value;
            }
        }

        /// <remarks/>
        public string codiceSisal
        {
            get
            {
                return this.codiceSisalField;
            }
            set
            {
                this.codiceSisalField = value;
            }
        }

        /// <remarks/>
        public string progRata
        {
            get
            {
                return this.progRataField;
            }
            set
            {
                this.progRataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class headerCreditiType
    {

        private comunicazioneType comunicazioneField;

        /// <remarks/>
        public comunicazioneType comunicazione
        {
            get
            {
                return this.comunicazioneField;
            }
            set
            {
                this.comunicazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class comunicazioneType
    {

        private string intestazioneUfficioField;

        private string oggettoLetteraField;

        private string testoLiberoField;

        private string firmaField;

        private string firmaRespProcField;

        private string testoFirmaSostitutivaField;

        /// <remarks/>
        public string intestazioneUfficio
        {
            get
            {
                return this.intestazioneUfficioField;
            }
            set
            {
                this.intestazioneUfficioField = value;
            }
        }

        /// <remarks/>
        public string oggettoLettera
        {
            get
            {
                return this.oggettoLetteraField;
            }
            set
            {
                this.oggettoLetteraField = value;
            }
        }

        /// <remarks/>
        public string testoLibero
        {
            get
            {
                return this.testoLiberoField;
            }
            set
            {
                this.testoLiberoField = value;
            }
        }

        /// <remarks/>
        public string firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }

        /// <remarks/>
        public string firmaRespProc
        {
            get
            {
                return this.firmaRespProcField;
            }
            set
            {
                this.firmaRespProcField = value;
            }
        }

        /// <remarks/>
        public string testoFirmaSostitutiva
        {
            get
            {
                return this.testoFirmaSostitutivaField;
            }
            set
            {
                this.testoFirmaSostitutivaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class scartoCreditoExtType
    {

        private string tipoScartoField;

        private string descrizioneScartoField;

        /// <remarks/>
        public string TipoScarto
        {
            get
            {
                return this.tipoScartoField;
            }
            set
            {
                this.tipoScartoField = value;
            }
        }

        /// <remarks/>
        public string DescrizioneScarto
        {
            get
            {
                return this.descrizioneScartoField;
            }
            set
            {
                this.descrizioneScartoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class variazioneType
    {

        private string tipoField;

        private long[] idPosizioneField;

        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idPosizione")]
        public long[] idPosizione
        {
            get
            {
                return this.idPosizioneField;
            }
            set
            {
                this.idPosizioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class versamentoRispostaSisalType
    {

        private string universalKeyField;

        /// <remarks/>
        public string universalKey
        {
            get
            {
                return this.universalKeyField;
            }
            set
            {
                this.universalKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class rispostaSisalType
    {

        private int scartatoField;

        private versamentoRispostaSisalType[] versamentoField;

        /// <remarks/>
        public int scartato
        {
            get
            {
                return this.scartatoField;
            }
            set
            {
                this.scartatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("versamento")]
        public versamentoRispostaSisalType[] versamento
        {
            get
            {
                return this.versamentoField;
            }
            set
            {
                this.versamentoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class scartoPosteFtpType
    {

        private string universalKeyField;

        /// <remarks/>
        public string universalKey
        {
            get
            {
                return this.universalKeyField;
            }
            set
            {
                this.universalKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class versamentoPosteFtpType
    {

        private string universalKeyField;

        /// <remarks/>
        public string universalKey
        {
            get
            {
                return this.universalKeyField;
            }
            set
            {
                this.universalKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class rispostaPosteFtpType
    {

        private string fileNameField;

        private versamentoPosteFtpType[] versamentiField;

        private scartoPosteFtpType[] scartatiField;

        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("versamento", IsNullable = false)]
        public versamentoPosteFtpType[] versamenti
        {
            get
            {
                return this.versamentiField;
            }
            set
            {
                this.versamentiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("scarto", IsNullable = false)]
        public scartoPosteFtpType[] scartati
        {
            get
            {
                return this.scartatiField;
            }
            set
            {
                this.scartatiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class scartoType
    {

        private string progPosizioneField;

        private string tipoScartoField;

        private string descrizioneScartoField;

        /// <remarks/>
        public string ProgPosizione
        {
            get
            {
                return this.progPosizioneField;
            }
            set
            {
                this.progPosizioneField = value;
            }
        }

        /// <remarks/>
        public string TipoScarto
        {
            get
            {
                return this.tipoScartoField;
            }
            set
            {
                this.tipoScartoField = value;
            }
        }

        /// <remarks/>
        public string DescrizioneScarto
        {
            get
            {
                return this.descrizioneScartoField;
            }
            set
            {
                this.descrizioneScartoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    public partial class protocolloSirType
    {

        private string numeroEmissioneSirField;

        private string tipoDocumentoSirField;

        private string tipoProtocolloField;

        private string progressivoProtocolloField;

        private string annoProtocolloField;

        private System.DateTime dataProtocolloField;

        private bool dataProtocolloFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string numeroEmissioneSir
        {
            get
            {
                return this.numeroEmissioneSirField;
            }
            set
            {
                this.numeroEmissioneSirField = value;
            }
        }

        /// <remarks/>
        public string tipoDocumentoSir
        {
            get
            {
                return this.tipoDocumentoSirField;
            }
            set
            {
                this.tipoDocumentoSirField = value;
            }
        }

        /// <remarks/>
        public string tipoProtocollo
        {
            get
            {
                return this.tipoProtocolloField;
            }
            set
            {
                this.tipoProtocolloField = value;
            }
        }

        /// <remarks/>
        public string progressivoProtocollo
        {
            get
            {
                return this.progressivoProtocolloField;
            }
            set
            {
                this.progressivoProtocolloField = value;
            }
        }

        /// <remarks/>
        public string annoProtocollo
        {
            get
            {
                return this.annoProtocolloField;
            }
            set
            {
                this.annoProtocolloField = value;
            }
        }

        /// <remarks/>
        public System.DateTime dataProtocollo
        {
            get
            {
                return this.dataProtocolloField;
            }
            set
            {
                this.dataProtocolloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataProtocolloSpecified
        {
            get
            {
                return this.dataProtocolloFieldSpecified;
            }
            set
            {
                this.dataProtocolloFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class strutturaType
    {

        private string settoreField;

        private string areaField;

        private string cdrField;

        private string specTributoField;

        private string enteCreditoreField;

        /// <remarks/>
        public string settore
        {
            get
            {
                return this.settoreField;
            }
            set
            {
                this.settoreField = value;
            }
        }

        /// <remarks/>
        public string area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        public string cdr
        {
            get
            {
                return this.cdrField;
            }
            set
            {
                this.cdrField = value;
            }
        }

        /// <remarks/>
        public string specTributo
        {
            get
            {
                return this.specTributoField;
            }
            set
            {
                this.specTributoField = value;
            }
        }

        /// <remarks/>
        public string enteCreditore
        {
            get
            {
                return this.enteCreditoreField;
            }
            set
            {
                this.enteCreditoreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class recapitoType
    {

        private string tipoField;

        private string descrizioneField;

        private string capField;

        private string comuneField;

        private string frazioneField;

        private string provinciaField;

        private string aggiuntiveEdifField;

        private string pressoField;

        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        public string descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        public string cap
        {
            get
            {
                return this.capField;
            }
            set
            {
                this.capField = value;
            }
        }

        /// <remarks/>
        public string comune
        {
            get
            {
                return this.comuneField;
            }
            set
            {
                this.comuneField = value;
            }
        }

        /// <remarks/>
        public string frazione
        {
            get
            {
                return this.frazioneField;
            }
            set
            {
                this.frazioneField = value;
            }
        }

        /// <remarks/>
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }

        /// <remarks/>
        public string aggiuntiveEdif
        {
            get
            {
                return this.aggiuntiveEdifField;
            }
            set
            {
                this.aggiuntiveEdifField = value;
            }
        }

        /// <remarks/>
        public string presso
        {
            get
            {
                return this.pressoField;
            }
            set
            {
                this.pressoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class anagraficaType
    {

        private int progressivoField;

        private string codiceField;

        private string personaField;

        private string soggettoField;

        private string cognomeField;

        private string nomeField;

        private string denominazioneField;

        private string nascitaField;

        private string localitaField;

        private string provinciaField;

        private string cfField;

        private string pivaField;

        private string sessoField;

        /// <remarks/>
        public int progressivo
        {
            get
            {
                return this.progressivoField;
            }
            set
            {
                this.progressivoField = value;
            }
        }

        /// <remarks/>
        public string codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        public string persona
        {
            get
            {
                return this.personaField;
            }
            set
            {
                this.personaField = value;
            }
        }

        /// <remarks/>
        public string soggetto
        {
            get
            {
                return this.soggettoField;
            }
            set
            {
                this.soggettoField = value;
            }
        }

        /// <remarks/>
        public string cognome
        {
            get
            {
                return this.cognomeField;
            }
            set
            {
                this.cognomeField = value;
            }
        }

        /// <remarks/>
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        public string denominazione
        {
            get
            {
                return this.denominazioneField;
            }
            set
            {
                this.denominazioneField = value;
            }
        }

        /// <remarks/>
        public string nascita
        {
            get
            {
                return this.nascitaField;
            }
            set
            {
                this.nascitaField = value;
            }
        }

        /// <remarks/>
        public string localita
        {
            get
            {
                return this.localitaField;
            }
            set
            {
                this.localitaField = value;
            }
        }

        /// <remarks/>
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }

        /// <remarks/>
        public string cf
        {
            get
            {
                return this.cfField;
            }
            set
            {
                this.cfField = value;
            }
        }

        /// <remarks/>
        public string piva
        {
            get
            {
                return this.pivaField;
            }
            set
            {
                this.pivaField = value;
            }
        }

        /// <remarks/>
        public string sesso
        {
            get
            {
                return this.sessoField;
            }
            set
            {
                this.sessoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class soggettoType
    {

        private anagraficaType[] personaField;

        private recapitoType[] recapitiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona")]
        public anagraficaType[] persona
        {
            get
            {
                return this.personaField;
            }
            set
            {
                this.personaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recapiti")]
        public recapitoType[] recapiti
        {
            get
            {
                return this.recapitiField;
            }
            set
            {
                this.recapitiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class dettaglioType
    {

        private string progPosizioneField;

        private string progOggettoField;

        private System.DateTime datainizioField;

        private System.DateTime datafineField;

        private string tipooggettoField;

        private string descrizioneoggettoField;

        private string codRotazioneField;

        private string tipoPosizioneField;

        private variazioneType variazioneField;

        /// <remarks/>
        public string progPosizione
        {
            get
            {
                return this.progPosizioneField;
            }
            set
            {
                this.progPosizioneField = value;
            }
        }

        /// <remarks/>
        public string progOggetto
        {
            get
            {
                return this.progOggettoField;
            }
            set
            {
                this.progOggettoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime datainizio
        {
            get
            {
                return this.datainizioField;
            }
            set
            {
                this.datainizioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime datafine
        {
            get
            {
                return this.datafineField;
            }
            set
            {
                this.datafineField = value;
            }
        }

        /// <remarks/>
        public string tipooggetto
        {
            get
            {
                return this.tipooggettoField;
            }
            set
            {
                this.tipooggettoField = value;
            }
        }

        /// <remarks/>
        public string descrizioneoggetto
        {
            get
            {
                return this.descrizioneoggettoField;
            }
            set
            {
                this.descrizioneoggettoField = value;
            }
        }

        /// <remarks/>
        public string codRotazione
        {
            get
            {
                return this.codRotazioneField;
            }
            set
            {
                this.codRotazioneField = value;
            }
        }

        /// <remarks/>
        public string tipoPosizione
        {
            get
            {
                return this.tipoPosizioneField;
            }
            set
            {
                this.tipoPosizioneField = value;
            }
        }

        /// <remarks/>
        public variazioneType variazione
        {
            get
            {
                return this.variazioneField;
            }
            set
            {
                this.variazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class rataType
    {

        private int progrataField;

        private bool progrataFieldSpecified;

        private string datascadenzaField;

        /// <remarks/>
        public int prograta
        {
            get
            {
                return this.progrataField;
            }
            set
            {
                this.progrataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool progrataSpecified
        {
            get
            {
                return this.progrataFieldSpecified;
            }
            set
            {
                this.progrataFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string datascadenza
        {
            get
            {
                return this.datascadenzaField;
            }
            set
            {
                this.datascadenzaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class praticaType
    {

        private int numeroriferimentoField;

        private string datariferimentoField;

        private int annoriferimentoField;

        private bool annoriferimentoFieldSpecified;

        private int numeroprotocolloField;

        private bool numeroprotocolloFieldSpecified;

        private string dataprotocolloField;

        private string datanotificaField;

        private string tipoField;

        /// <remarks/>
        public int numeroriferimento
        {
            get
            {
                return this.numeroriferimentoField;
            }
            set
            {
                this.numeroriferimentoField = value;
            }
        }

        /// <remarks/>
        public string datariferimento
        {
            get
            {
                return this.datariferimentoField;
            }
            set
            {
                this.datariferimentoField = value;
            }
        }

        /// <remarks/>
        public int annoriferimento
        {
            get
            {
                return this.annoriferimentoField;
            }
            set
            {
                this.annoriferimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool annoriferimentoSpecified
        {
            get
            {
                return this.annoriferimentoFieldSpecified;
            }
            set
            {
                this.annoriferimentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int numeroprotocollo
        {
            get
            {
                return this.numeroprotocolloField;
            }
            set
            {
                this.numeroprotocolloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroprotocolloSpecified
        {
            get
            {
                return this.numeroprotocolloFieldSpecified;
            }
            set
            {
                this.numeroprotocolloFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string dataprotocollo
        {
            get
            {
                return this.dataprotocolloField;
            }
            set
            {
                this.dataprotocolloField = value;
            }
        }

        /// <remarks/>
        public string datanotifica
        {
            get
            {
                return this.datanotificaField;
            }
            set
            {
                this.datanotificaField = value;
            }
        }

        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class voceType
    {

        private string codiceCNCField;

        private int annoField;

        private decimal importoField;

        private string scritturacontabileField;

        private int numerorataField;

        private bool numerorataFieldSpecified;

        private System.DateTime datascadenzaField;

        private bool datascadenzaFieldSpecified;

        private string codPostelField;

        private string codSisalField;

        private decimal importoVersatoField;

        private bool importoVersatoFieldSpecified;

        private string codRotazioneField;

        private string tipoPosizioneField;

        private decimal importoDovutoPrecField;

        private bool importoDovutoPrecFieldSpecified;

        private string tipoGruppoField;

        private string sisareIdField;

        private string progRataField;

        private string riferimentoVoceField;

        private string siglaSisareBenefField;

        /// <remarks/>
        public string codiceCNC
        {
            get
            {
                return this.codiceCNCField;
            }
            set
            {
                this.codiceCNCField = value;
            }
        }

        /// <remarks/>
        public int anno
        {
            get
            {
                return this.annoField;
            }
            set
            {
                this.annoField = value;
            }
        }

        /// <remarks/>
        public decimal importo
        {
            get
            {
                return this.importoField;
            }
            set
            {
                this.importoField = value;
            }
        }

        /// <remarks/>
        public string scritturacontabile
        {
            get
            {
                return this.scritturacontabileField;
            }
            set
            {
                this.scritturacontabileField = value;
            }
        }

        /// <remarks/>
        public int numerorata
        {
            get
            {
                return this.numerorataField;
            }
            set
            {
                this.numerorataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numerorataSpecified
        {
            get
            {
                return this.numerorataFieldSpecified;
            }
            set
            {
                this.numerorataFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime datascadenza
        {
            get
            {
                return this.datascadenzaField;
            }
            set
            {
                this.datascadenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datascadenzaSpecified
        {
            get
            {
                return this.datascadenzaFieldSpecified;
            }
            set
            {
                this.datascadenzaFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string codPostel
        {
            get
            {
                return this.codPostelField;
            }
            set
            {
                this.codPostelField = value;
            }
        }

        /// <remarks/>
        public string codSisal
        {
            get
            {
                return this.codSisalField;
            }
            set
            {
                this.codSisalField = value;
            }
        }

        /// <remarks/>
        public decimal importoVersato
        {
            get
            {
                return this.importoVersatoField;
            }
            set
            {
                this.importoVersatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importoVersatoSpecified
        {
            get
            {
                return this.importoVersatoFieldSpecified;
            }
            set
            {
                this.importoVersatoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string codRotazione
        {
            get
            {
                return this.codRotazioneField;
            }
            set
            {
                this.codRotazioneField = value;
            }
        }

        /// <remarks/>
        public string tipoPosizione
        {
            get
            {
                return this.tipoPosizioneField;
            }
            set
            {
                this.tipoPosizioneField = value;
            }
        }

        /// <remarks/>
        public decimal importoDovutoPrec
        {
            get
            {
                return this.importoDovutoPrecField;
            }
            set
            {
                this.importoDovutoPrecField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importoDovutoPrecSpecified
        {
            get
            {
                return this.importoDovutoPrecFieldSpecified;
            }
            set
            {
                this.importoDovutoPrecFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string tipoGruppo
        {
            get
            {
                return this.tipoGruppoField;
            }
            set
            {
                this.tipoGruppoField = value;
            }
        }

        /// <remarks/>
        public string sisareId
        {
            get
            {
                return this.sisareIdField;
            }
            set
            {
                this.sisareIdField = value;
            }
        }

        /// <remarks/>
        public string progRata
        {
            get
            {
                return this.progRataField;
            }
            set
            {
                this.progRataField = value;
            }
        }

        /// <remarks/>
        public string riferimentoVoce
        {
            get
            {
                return this.riferimentoVoceField;
            }
            set
            {
                this.riferimentoVoceField = value;
            }
        }

        /// <remarks/>
        public string siglaSisareBenef
        {
            get
            {
                return this.siglaSisareBenefField;
            }
            set
            {
                this.siglaSisareBenefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class posizioneType
    {

        private dettaglioType[] dettaglioField;

        private praticaType praticaField;

        private rataType[] rataField;

        private soggettoType[] soggettoField;

        private voceType[] voceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dettaglio")]
        public dettaglioType[] dettaglio
        {
            get
            {
                return this.dettaglioField;
            }
            set
            {
                this.dettaglioField = value;
            }
        }

        /// <remarks/>
        public praticaType pratica
        {
            get
            {
                return this.praticaField;
            }
            set
            {
                this.praticaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rata")]
        public rataType[] rata
        {
            get
            {
                return this.rataField;
            }
            set
            {
                this.rataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("soggetto")]
        public soggettoType[] soggetto
        {
            get
            {
                return this.soggettoField;
            }
            set
            {
                this.soggettoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voce")]
        public voceType[] voce
        {
            get
            {
                return this.voceField;
            }
            set
            {
                this.voceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class creditoType
    {

        private strutturaType strutturaField;

        private posizioneType[] posizioniField;

        /// <remarks/>
        public strutturaType struttura
        {
            get
            {
                return this.strutturaField;
            }
            set
            {
                this.strutturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("posizioni")]
        public posizioneType[] posizioni
        {
            get
            {
                return this.posizioniField;
            }
            set
            {
                this.posizioniField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute("creditoExt", Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class creditoTypeExt
    {

        private long lottoField;

        private string progPosizioneField;

        private string idPosCreditoriaField;

        private scartoCreditoExtType scartoField;

        /// <remarks/>
        public long lotto
        {
            get
            {
                return this.lottoField;
            }
            set
            {
                this.lottoField = value;
            }
        }

        /// <remarks/>
        public string progPosizione
        {
            get
            {
                return this.progPosizioneField;
            }
            set
            {
                this.progPosizioneField = value;
            }
        }

        /// <remarks/>
        public string idPosCreditoria
        {
            get
            {
                return this.idPosCreditoriaField;
            }
            set
            {
                this.idPosCreditoriaField = value;
            }
        }

        /// <remarks/>
        public scartoCreditoExtType scarto
        {
            get
            {
                return this.scartoField;
            }
            set
            {
                this.scartoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute("creditiExt", Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class creditiExtType
    {

        private creditoTypeExt[] creditoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("credito")]
        public creditoTypeExt[] credito
        {
            get
            {
                return this.creditoField;
            }
            set
            {
                this.creditoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.capgemini.it/cdr/io")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.capgemini.it/cdr/io", IsNullable = false)]
    public partial class crediti
    {

        private headerCreditiType headerField;

        private creditoType[] creditoField;

        /// <remarks/>
        public headerCreditiType header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("credito")]
        public creditoType[] credito
        {
            get
            {
                return this.creditoField;
            }
            set
            {
                this.creditoField = value;
            }
        }
    }
}
