//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3053
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Com.Unisys.CdR.Certi.Objects {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoMD.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/CertificatoMD.xsd", IsNullable=false)]
    public partial class CertificatoMD {
        
        private CertificatoMDData dataField;
        
        /// <remarks/>
        public CertificatoMDData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoMD.xsd")]
    public partial class CertificatoMDData {
        
        private CertificatoMDDataDoc docField;
        
        private CertificatoMDDataBlobFile blobFileField;
        
        /// <remarks/>
        public CertificatoMDDataDoc Doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
            }
        }
        
        /// <remarks/>
        public CertificatoMDDataBlobFile BlobFile {
            get {
                return this.blobFileField;
            }
            set {
                this.blobFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoMD.xsd")]
    public partial class CertificatoMDDataDoc {
        
        private string cIUField;
        
        private string codiceFiscaleField;
        
        private System.DateTime dataEmissioneField;
        
        private string extensionField;
        
        /// <remarks/>
        public string CIU {
            get {
                return this.cIUField;
            }
            set {
                this.cIUField = value;
            }
        }
        
        /// <remarks/>
        public string CodiceFiscale {
            get {
                return this.codiceFiscaleField;
            }
            set {
                this.codiceFiscaleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataEmissione {
            get {
                return this.dataEmissioneField;
            }
            set {
                this.dataEmissioneField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoMD.xsd")]
    public partial class CertificatoMDDataBlobFile {
        
        private byte[] hashField;
        
        private string formatoField;
        
        private string dimensioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        public string Formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
            }
        }
        
        /// <remarks/>
        public string Dimensione {
            get {
                return this.dimensioneField;
            }
            set {
                this.dimensioneField = value;
            }
        }
    }
}
