//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3053
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Com.Unisys.CdR.Certi.Objects {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoDoc.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/CertificatoDoc.xsd", IsNullable=false)]
    public partial class CertificatoDoc {
        
        private CertificatoDocData dataField;
        
        /// <remarks/>
        public CertificatoDocData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoDoc.xsd")]
    public partial class CertificatoDocData {
        
        private CertificatoDocDataIndex indexField;
        
        private byte[] blobFileField;
        
        /// <remarks/>
        public CertificatoDocDataIndex Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BlobFile {
            get {
                return this.blobFileField;
            }
            set {
                this.blobFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CertificatoDoc.xsd")]
    public partial class CertificatoDocDataIndex {
        
        private string cIUField;
        
        private byte[] handleField;
        
        private string codiceFiscaleField;
        
        private System.DateTime dataEmissioneField;
        
        private string extensionField;
        
        private int iDCertificatoField;

        private int status;
        
        /// <remarks/>
        public string CIU {
            get {
                return this.cIUField;
            }
            set {
                this.cIUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] Handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        public string CodiceFiscale {
            get {
                return this.codiceFiscaleField;
            }
            set {
                this.codiceFiscaleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataEmissione {
            get {
                return this.dataEmissioneField;
            }
            set {
                this.dataEmissioneField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }

        /// <remarks/>
        public int Status {
            get {
                return this.status;
            }
            set {
                this.status = value;
            }
        }

        /// <remarks/>
        public int IDCertificato {
            get {
                return this.iDCertificatoField;
            }
            set {
                this.iDCertificatoField = value;
            }
        }
    }
}
