//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
// 
#pragma warning disable 1591

namespace Com.Unisys.CdR.Certi.WebApp.Business.ProxyPagamentiWS
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;



    [System.Web.Services.WebServiceBindingAttribute(Name = "Pagamento_CertificatiSOAPSoapBinding", Namespace = "http://roma.pol.eng.it/Pagamento_Certificati/ws")]
    public partial class Pagamento_Certificati : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        private bool useDefaultCredentialsSetExplicitly;

        public Pagamento_Certificati()
        {
            this.Url = "http://10.150.130.37:6080/CDRServices/services/Pagamento_CertificatiSOAP";
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://roma.pol.eng.it/Pagamento_Certificati/ws/ListaTransazioni", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlAnyElement()]
        public System.Xml.XmlNode ListaTransazioni([System.Xml.Serialization.XmlArrayAttribute(Namespace = "http://roma.pol.eng.it/Pagamento_Certificati/ws")] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] string[] ListaTransazioniRequest)
        {
            object[] results = this.Invoke("ListaTransazioni", new object[] {
                        ListaTransazioniRequest});
            return ((System.Xml.XmlNode)(results[0]));
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }
}

#pragma warning restore 1591